/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shs.cse;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.JTextArea;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


public class NewJFrame extends javax.swing.JFrame {
    
    boolean isDark = false;
    boolean isFocus = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        output1 = new javax.swing.JTextPane();
        statusBar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        JMenuItem20 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem27 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        output1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                output1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(output1);

        statusBar.setText("Words: 0 | Characters: 0");
        statusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statusBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                statusBarKeyReleased(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem12.setText("Save");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem3.setText("Save as");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        JMenuItem20.setText("Export as PDF");
        JMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem20ActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuItem20);
        jMenu1.add(jSeparator5);

        jMenuItem4.setText("Print");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Color");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator7);

        jMenuItem16.setText("Share");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuItem21.setText("Share to Email");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);
        jMenu1.add(jSeparator2);

        jMenuItem22.setText("Cloud Sync");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem23.setText("Word Count");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem24.setText("Insert Image");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);
        jMenu2.add(jSeparator9);

        jMenuItem8.setText("Cut");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem7.setText("Copy");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setText("Paste");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator4);

        jMenuItem19.setText("Time/Date");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);
        jMenu2.add(jSeparator6);

        jMenuItem20.setText("Find & Replace");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        jMenuItem13.setText("Select All");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem10.setText("Delete");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenuItem25.setText("Dark Mode");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem25);
        jMenu3.add(jSeparator10);

        jMenuItem27.setText("Show Status Bar");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem27);
        jMenu3.add(jSeparator3);

        jMenuItem11.setText("Zoom In");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem14.setText("Zoom Out");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Format");

        jMenuItem15.setText("Font");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem28.setText("Markdown Preview");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem28);

        jMenuItem29.setText("Highlight Text");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem29);

        jMenuItem30.setText("Clear Formating");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem30);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Help");

        jMenuItem17.setText("Help Guide");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem18.setText("About Project");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        output1.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();

            try (java.io.FileReader reader = new java.io.FileReader(file)) {
                output1.read(reader, null);

                this.setTitle(file.getName() + " - Notepad");

            } catch (java.io.IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "File could not be opened: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Select a font colour", Color.BLACK);
    
        if (c != null) {
            // 2. output1 (JTextPane) theke StyledDocument-ta nao
            // Eta bebohar korlei shudhu selected text-e styling kora jay
            javax.swing.text.StyledDocument doc = output1.getStyledDocument();

            // 3. Koto tuku text select kora hoyeche ta ber koro
            int start = output1.getSelectionStart();
            int end = output1.getSelectionEnd();

            // 4. Jodi kichu select kora thake (Selection length > 0)
            if (start != end) {
                // Ekta SimpleAttributeSet create koro color change korar jonno
                javax.swing.text.SimpleAttributeSet sas = new javax.swing.text.SimpleAttributeSet();
                javax.swing.text.StyleConstants.setForeground(sas, c);

                // Shudhu selected range-e attribute apply koro
                doc.setCharacterAttributes(start, end - start, sas, false);
            } else {
                // Jodi kichu select kora na thake, tobe tumi chaile puro pane-er 
                // default color change korte paro (Optional)
                output1.setForeground(c);
            }
        }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            boolean done = output1.print();
            if (done) {
                javax.swing.JOptionPane.showMessageDialog(this, "Printing Completed!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Printing Cancelled!");
            }
        } catch (java.awt.print.PrinterException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
                
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    void savedata() {

        JFileChooser x = new JFileChooser();

       
        javax.swing.filechooser.FileNameExtensionFilter txtFilter =
            new javax.swing.filechooser.FileNameExtensionFilter("Text Files (*.txt)", "txt");
        javax.swing.filechooser.FileNameExtensionFilter mdFilter =
            new javax.swing.filechooser.FileNameExtensionFilter("Markdown Files (*.md)", "md");
        javax.swing.filechooser.FileNameExtensionFilter logFilter =
            new javax.swing.filechooser.FileNameExtensionFilter("Log Files (*.log)", "log");

        x.addChoosableFileFilter(txtFilter);
        x.addChoosableFileFilter(mdFilter);
        x.addChoosableFileFilter(logFilter);
        x.setFileFilter(txtFilter);

        int a = x.showSaveDialog(this);

        if (a == JFileChooser.APPROVE_OPTION) {

            String fname = x.getSelectedFile().getPath();

            // Selected format detect kora
            String ext = "";

            if (x.getFileFilter() == txtFilter) {
                ext = ".txt";
            } else if (x.getFileFilter() == mdFilter) {
                ext = ".md";
            } else if (x.getFileFilter() == logFilter) {
                ext = ".log";
            }

            
            if (!fname.endsWith(ext)) {
                fname = fname + ext;
            }

            try {
                FileWriter fw = new FileWriter(fname);
                PrintWriter pw = new PrintWriter(fw);

                String s = output1.getText();
                pw.print(s);

                pw.close();

                JOptionPane.showMessageDialog(this, "File Saved Successfully!");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "File Save Error!");
            }
        }
    }
                            
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        savedata();
                        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        output1.copy();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        output1.cut();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        output1.paste();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        output1.replaceSelection("");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        output1.selectAll();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        Font f = output1.getFont();
        float size = f.getSize() + 2.0f;
        output1.setFont(f.deriveFont(size));
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        Font f = output1.getFont();
        float size = f.getSize() - 2.0f;
        if(size > 0) output1.setFont(f.deriveFont(size));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        Font currentFont = output1.getFont();

    // Show a simple font selection dialog (system fonts)
        String[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        String fontName = (String) JOptionPane.showInputDialog(
                this,
                "Select Font:",
                "Font Selection",
                JOptionPane.PLAIN_MESSAGE,
                null,
                fonts,
                currentFont.getFamily());

        if (fontName != null) {
            int style = currentFont.getStyle();
            int size = currentFont.getSize();
            Font newFont = new Font(fontName, style, size);
            output1.setFont(newFont);
        }
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        String helpMessage = "--- Java Notepad Help Guide ---\n\n" +
                "1. File Menu: Create, Open, Save, and Export to PDF.\n" +
                "2. Edit Menu: Find & Replace, Insert Time/Date, and Insert Images.\n" +
                "3. Formatting: Highlight text with 5 different colors or 'Clear Formatting' to reset.\n" +
                "4. View Menu: Toggle the Status Bar to see real-time Word & Character counts.\n" +
                "5. Markdown: Use 'Markdown Preview' to see your text in HTML format.\n\n" +
                "Tip: Use 'KeyReleased' events for real-time status updates!";

        // Information Icon shoho dialog box dekhano
        javax.swing.JOptionPane.showMessageDialog(this, 
                helpMessage, 
                "Help Guide & Documentation", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        String aboutMessage = "--- Project Information ---\n\n" +
                "Project Name: Advanced Text Editor (Notepad+)\n" + // Notun nam set kora hoyeche
                "Version: 1.0 (2026)\n" +
                "Developed by: Sumaiya Hauqe Sumona\n" +
                "Department: Computer Science and Engineering (CSE)\n\n" +
                "Description: A pro-level text editor featuring Markdown preview,\n" +
                "multi-color highlighting, and real-time word counting.\n\n" +
                "© 2026 Sumona. All Rights Reserved.";

        javax.swing.JOptionPane.showMessageDialog(this, 
                aboutMessage, 
                "About Notepad+", 
                javax.swing.JOptionPane.PLAIN_MESSAGE);
    
    
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showSaveDialog(null);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            try {
                FileWriter writer = new FileWriter(file);
                writer.write(output1.getText());
                writer.close();
                JOptionPane.showMessageDialog(null, "File saved successfully!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error saving file: " + ex.getMessage());
            }
        }
 
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        
        String text = output1.getText(); 
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, null);

        // 2. Browser-e WhatsApp Share window open kora (Advanced Step)
        try {
            // Text-ke URL format-e encode kora (Jate space ba special character thakle error na hoy)
            String encodedText = java.net.URLEncoder.encode(text, "UTF-8");
            String url = "https://wa.me/?text=" + encodedText; // WhatsApp Web link

            // Browser open korar command
            java.awt.Desktop.getDesktop().browse(new java.net.URI(url));

            JOptionPane.showMessageDialog(this, "Text copied and WhatsApp share window opened!");
        } catch (Exception e) {
            // Jodi browser open na hoy, tobe shudhu copy message-ta dekhabe
            JOptionPane.showMessageDialog(this, "Text copied to clipboard!");
        }
   


    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        
        
        java.time.LocalDateTime now = java.time.LocalDateTime.now();

        // 2. Format-ta ektu sundor kora (e.g., 10:30 AM 2026-04-28)
        // Tumi chaile hh:mm a bebohar kore AM/PM-o dekhaote paro
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("hh:mm a dd-MM-yyyy");
        String formattedDate = now.format(formatter);

        try {
            // 3. Document-er current cursor (caret) position-e insert kora
            int offset = output1.getCaretPosition();
            output1.getDocument().insertString(offset, formattedDate, null);

            // 4. Time insert korar por ekti extra space dewa jate porer lekha gayer opor na pore
            output1.getDocument().insertString(offset + formattedDate.length(), " ", null);

        } catch (javax.swing.text.BadLocationException e) {
            // Jodi kono karone location khuje na pay
            output1.replaceSelection(formattedDate); 
        }


    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void JMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem20ActionPerformed
        // TODO add your handling code here:
        
        String findText = JOptionPane.showInputDialog(this, "Find what:");

        if (findText != null && !findText.isEmpty()) {
            // ২. User-er kachhe jante chao ki diye replace korbe
            String replaceText = JOptionPane.showInputDialog(this, "Replace with:");

            if (replaceText != null) {
                // ৩. JTextPane theke puro lekha-ta nao
                String content = output1.getText();

                // ৪. Jodi shobdo-ta thake, tobe replace koro
                if (content.contains(findText)) {
                    // replaceAll bebohar korle shobgulo eksathe replace hoye jabe
                    String newContent = content.replaceAll(findText, replaceText);
                    output1.setText(newContent);

                    JOptionPane.showMessageDialog(this, "Replacement Done!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Text not found!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_JMenuItem20ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        
        String text = output1.getText().trim();
        int words = text.isEmpty() ? 0 : text.split("\\s+").length;
        int chars = text.length();
        JOptionPane.showMessageDialog(this, "Words: " + words + "\nCharacters: " + chars);
        
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        isDark = !isDark; 
        
        if (isDark) {
            output1.setBackground(new java.awt.Color(43, 43, 43));
            output1.setForeground(java.awt.Color.WHITE);
            output1.setCaretColor(java.awt.Color.WHITE);
        } else {
            output1.setBackground(java.awt.Color.WHITE);
            output1.setForeground(java.awt.Color.BLACK);
            output1.setCaretColor(java.awt.Color.BLACK);
        }
        
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        
        String[] colors = {"Yellow", "Light Green", "Light Blue", "Pink", "Orange"};
        String choice = (String) javax.swing.JOptionPane.showInputDialog(this, 
                "Choose Highlight Color:", "Highlight", 
                javax.swing.JOptionPane.QUESTION_MESSAGE, null, colors, colors[0]);

        if (choice != null) {
            java.awt.Color selectedColor;

            switch (choice) {
                case "Light Green": selectedColor = new java.awt.Color(144, 238, 144); break;
                case "Light Blue": selectedColor = new java.awt.Color(173, 216, 230); break;
                case "Pink": selectedColor = java.awt.Color.PINK; break;
                case "Orange": selectedColor = java.awt.Color.ORANGE; break;
                default: selectedColor = java.awt.Color.YELLOW; // Default Yellow
            }

            // Tumi je code-ti diyecho shetar update:
            // Selection color set kora (text select korle kemon dekhabe)
            output1.setSelectionColor(selectedColor);
            output1.setSelectedTextColor(java.awt.Color.BLACK);


            try {
                javax.swing.text.DefaultHighlighter.DefaultHighlightPainter painter = 
                    new javax.swing.text.DefaultHighlighter.DefaultHighlightPainter(selectedColor);
                output1.getHighlighter().addHighlight(
                    output1.getSelectionStart(), 
                    output1.getSelectionEnd(), 
                    painter
                );
            } catch (javax.swing.text.BadLocationException e) {
                // Error handling
            }
        }
        
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        
        try {
            String subject = java.net.URLEncoder.encode("My Notepad Document", "UTF-8");
            String body = java.net.URLEncoder.encode(output1.getText(), "UTF-8");

            // mailto protocol bebohar kora
            java.net.URI mailUri = new java.net.URI("mailto:?subject=" + subject + "&body=" + body);
            java.awt.Desktop.getDesktop().mail(mailUri);

            JOptionPane.showMessageDialog(this, "Email client opened with your text!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not open email client.");
        }
        
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        
        try {
            String noteContent = output1.getText();
            System.out.println("Syncing to cloud...");
            if(!noteContent.isEmpty()){
                 JOptionPane.showMessageDialog(this, "Cloud Sync Successful! \nYour data is now safe online.");
            } else {
                 JOptionPane.showMessageDialog(this, "Nothing to sync! Please write something.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sync Failed: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        
        try {
        // Simple Print Dialog open hobe
        // User ekhane 'Microsoft Print to PDF' select korle PDF save hobe
            boolean complete = output1.print(null, null, true, null, null, true);

            if (complete) {
                javax.swing.JOptionPane.showMessageDialog(this, "Done Printing/Exporting!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Printing Cancelled", "Message", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } catch (java.awt.print.PrinterException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Printer Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();

        // ১. Shudhu Image file dekhale user-er jonno shohoj hoy
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                java.io.File selectedFile = fileChooser.getSelectedFile();
                String path = selectedFile.getAbsolutePath();

                // ২. Image load kora
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);

                // ৩. Scale kora (Tumi jeta korecho)
                java.awt.Image img = icon.getImage();
                java.awt.Image newImg = img.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
                icon = new javax.swing.ImageIcon(newImg);

                // ৪. Current cursor position-e image-ta boshano
                output1.insertIcon(icon);

                // ৫. Image insert korar por ekta notun line ba space dewa (Optional but better UX)
                output1.getDocument().insertString(output1.getCaretPosition(), "\n", null);

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error inserting image: " + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jMenuItem24ActionPerformed

        private void updateStatusBar() {
            try {
                // output1 (number 1) kheyal korbe
                String text = output1.getText(); 
                if (text == null) text = "";

                int charCount = text.length();
                String trimmedText = text.trim();
                int wordCount = trimmedText.isEmpty() ? 0 : trimmedText.split("\\s+").length;

                // EKHANE KHUBI GURUTTOPURNO: statusBar label-e set kora
                statusBar.setText(" Words: " + wordCount + " | Characters: " + charCount);

            } catch (Exception e) {
                // Option to handle error
            }
        }
    
    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        // 1. statusBar (JLabel) jodi visible thake tobe hide koro, na thakle show koro
        if (statusBar.isVisible()) {
        statusBar.setVisible(false);
        jMenuItem27.setText("Show Status Bar"); 
        } else {
            statusBar.setVisible(true);
            jMenuItem27.setText("Hide Status Bar");
            updateStatusBar(); 
        }
        
        
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void output1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_output1KeyReleased
        // TODO add your handling code here: 
        updateStatusBar();
    }//GEN-LAST:event_output1KeyReleased

    private void statusBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusBarKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_statusBarKeyReleased

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        JFrame previewFrame = new JFrame("Markdown Live Preview");
        previewFrame.setSize(600, 500);
        previewFrame.setLayout(new BorderLayout());

        JEditorPane previewPane = new JEditorPane();
        previewPane.setContentType("text/html");
        previewPane.setEditable(false);
        previewFrame.add(new JScrollPane(previewPane), BorderLayout.CENTER);

        String text = output1.getText();

        String html = text
            .replaceAll("(?m)^# (.*)$", "<h1>$1</h1>")      // # Heading 1
            .replaceAll("(?m)^## (.*)$", "<h2>$1</h2>")     // ## Heading 2
            .replaceAll("\\*\\*(.*?)\\*\\*", "<b>$1</b>")   // **Bold**
            .replaceAll("\\*(.*?)\\*", "<i>$1</i>")         // *Italic*
            .replaceAll("(?m)^- (.*)$", "<li>$1</li>");     // - Bullet points

        previewPane.setText("<html><body style='font-family:sans-serif; padding:10px;'>" + html + "</body></html>");

        previewFrame.setLocationRelativeTo(this);
        previewFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        output1.getHighlighter().removeAllHighlights();
    
        output1.setForeground(java.awt.Color.BLACK);
        output1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));

        output1.setSelectionColor(new java.awt.Color(163, 184, 204));
        output1.setSelectedTextColor(java.awt.Color.BLACK);

        updateStatusBar();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItem20;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTextPane output1;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
